server.port: 8082

# config.import traz os secrets e parameters da aws (LocalStack) para este arquivo env.
# O seed é feito pelo etc/aws/init.sh (parameters.csv / secrets.csv).
# prefix facilita o uso: ${billing.params.datasource.url}, ${billing.secrets.datasource.username}

spring:
  config:
    import:
      - aws-secretsmanager:/secret/algashop/billing/database?prefix=billing.secrets.datasource.
      - aws-secretsmanager:/secret/algashop/billing/fastpay?prefix=billing.secrets.fastpay.
      - aws-parameterstore:/config/algashop/billing?prefix=billing.params
      - aws-parameterstore:/config/algashop/shared?prefix=shared.params
  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566
      credentials:
        access-key: LSIAQAAAAAAVNCBMPNSG
        secret-key: test
  datasource:
    url: ${billing.params.datasource.url}
    username: ${billing.secrets.datasource.username}
    password: ${billing.secrets.datasource.password}
  jpa:
    show-sql: ${billing.params.jpa.show-sql}
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/testdata
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/billing
  security: # apontamos o resource para authorization server para ter validação e busca de chave públicas
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${shared.params.auth-server-url} # url de authorization server

logging:
  level:
    com.netflix.discovery.DiscoveryClient: OFF # desativa error eureka em dev
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF

algashop:
  integrations:
    payment:
      provider: FASTPAY
      fastpay:
        hostname: ${billing.params.fastpay.hostname}
        private-token: ${billing.secrets.fastpay.private-token}
        webhook-url: ${billing.params.fastpay.webhook-url}

eureka:
  client:
    serviceUrl:
      defaultZone: ${shared.params.service-registry-url}/eureka
    healthcheck:
      enabled: true # habilita o health em eureka para status de serviço dentro de eureka
  instance:
    instanceId: ${random.uuid} # cada instancia replicada ganha um id unico
    prefer-ip-address: true # configura rede alcançável via docker
